.TH SPEK 1 "2013\-04\-18" "User\[aq]s Guide" "Version 0.8.2"
.SH NAME
.PP
Spek \- Acoustic Spectrum Analyser
.SH SYNOPSIS
.PP
\f[C]spek\f[] [\f[I]OPTION\f[] \f[I]\&...\f[]] [\f[I]FILE\f[]]
.SH DESCRIPTION
.PP
\f[I]Spek\f[] generates a spectrogram for the input audio file.
.SH OPTIONS
.TP
.B \f[C]\-h\f[], \f[C]\-\-help\f[]
Output the help message then quit.
.RS
.RE
.TP
.B \f[C]\-V\f[], \f[C]\-\-version\f[]
Output version information then quit.
.RS
.RE
.SH KEYBINDINGS
.SS Notes
.PP
On OS X use the Command key instead of Ctrl.
.SS Menu
.TP
.B \f[C]Ctrl\-O\f[]
Open a new file.
.RS
.RE
.TP
.B \f[C]Ctrl\-S\f[]
Save the spectrogram as an image file.
.RS
.RE
.TP
.B \f[C]Ctrl\-E\f[]
Show the preferences dialog.
.RS
.RE
.TP
.B \f[C]F1\f[]
Open online manual in the browser.
.RS
.RE
.TP
.B \f[C]Shift\-F1\f[]
Show the about dialog.
.RS
.RE
.SS Spectrogram
.TP
.B \f[C]Ctrl\-up\f[], \f[C]Ctrl\-down\f[]
Change the lower limit of the dynamic range in dBFS.
.RS
.RE
.TP
.B \f[C]Ctrl\-Shift\-up\f[], \f[C]Ctrl\-Shift\-down\f[]
Change the upper limit of the dynamic range in dBFS.
.RS
.RE
.SH FILES
.TP
.B \f[I]~/.config/spek/preferences\f[]
The configuration file for \f[I]Spek\f[], stored in a simple INI format.
.RS
.RE
.SH AUTHORS
.PP
Alexander Kojevnikov <alexander@kojevnikov.com>.
Other contributors are listed in the LICENCE.md file distributed with
the source code.
.SH DISTRIBUTION
.PP
The latest version of \f[I]Spek\f[] may be downloaded from
<http://spek.cc>.
